// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfXl5mnJH_vZCwijvX8kKQ4beaxNDF4e0',
    appId: '1:371273133115:web:d0c787a2e48594103b401e',
    messagingSenderId: '371273133115',
    projectId: 'tawfeer-8fca0',
    authDomain: 'tawfeer-8fca0.firebaseapp.com',
    storageBucket: 'tawfeer-8fca0.appspot.com',
    measurementId: 'G-5E04MGWHW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClHnawIUBSkSd0_pAHN5iC1nwlpJ9Pwe0',
    appId: '1:371273133115:android:f6b2b6a82dc51e833b401e',
    messagingSenderId: '371273133115',
    projectId: 'tawfeer-8fca0',
    storageBucket: 'tawfeer-8fca0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz6qOWSe7mUfYVUP6qmCIP4lL5URww5gY',
    appId: '1:371273133115:ios:ca92efe8f64250863b401e',
    messagingSenderId: '371273133115',
    projectId: 'tawfeer-8fca0',
    storageBucket: 'tawfeer-8fca0.appspot.com',
    iosClientId: '371273133115-7187d4arjf62j531ivuinve0evq2psfq.apps.googleusercontent.com',
    iosBundleId: 'com.gatetechs.kishk.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz6qOWSe7mUfYVUP6qmCIP4lL5URww5gY',
    appId: '1:371273133115:ios:02fff952072be9cb3b401e',
    messagingSenderId: '371273133115',
    projectId: 'tawfeer-8fca0',
    storageBucket: 'tawfeer-8fca0.appspot.com',
    iosBundleId: 'com.gatetechs.kishk.driver.RunnerTests',
  );
}
